### ISSUE TITLE
How to print std::vector<std::string> into a row?

### ISSUE THREAD

**Issue by ManNam1** [p-ranav/tabulate#102]
I need to convert vectors of string into table rows, but failing to do that. Could you please help?

**Comment by ManNam1** [comment]
After some time I have come up with a solution (I suppose not the best): 
Table table;
    std::vector<variant<std::string, const char *, string_view, Table>> header;
    header.push_back("corner cell");
    for (auto element : some_vector_of_strings)
    {
        header.push_back(element );
    }
    table.add_row(Row_t{header});

**Comment by p-ranav** [comment]
Hello. You should be able to do this in one line:

```cpp
std::vector<std::string> stringVec{"A", "B", "C"}; // some vector of strings

Row_t header(stringVec.begin(), stringVec.end());
```

**Comment by ManNam1** [comment]
thank you very much, it works for me!
