### ISSUE TITLE
How do I initialize an n*m Table?

### ISSUE THREAD

**Issue by DGJGzy** [p-ranav/tabulate#105]
If only used `add_row`, it would be very difficult to initialize such a Table when n and m are variables.

**Comment by tannery-cerebras** [comment]
I had a similar issue.
I found the [mario example](https://github.com/p-ranav/tabulate/blob/25e610ed973ed306291fdafd791f760438b34f07/samples/mario.cpp) gave me my solution.

```c++
  Table table;
  for (size_t i = 0; i < rows; ++i) {
    Row_t row;
    for (size_t j = 0; j < cols; ++j) {
      row.push_back("");
    }
    table.add_row(row);
  }
```
