### ISSUE TITLE
Unexpected format when using Table output

### ISSUE THREAD

**Issue by neog24** [p-ranav/tabulate#118]
When I try to output the original raw string, the result is as expected as below:

```cpp
std::cout << plan->toString() << std::endl;
```

```txt
└──Project(v)
    └──Limit(1)
        └──HashJoin
            ├──DelimScan(1)
            └──DelimProduce(1)
                └──NodeScan
```

But when I try to put the result in a linenoise Table, the format was unexpected:

```cpp
Table outputTable;
outputTable.add_row({"Plan"});
outputTable.add_row({plan->toString()});
std::cout << outputTable << std::endl;
```

```txt
+--------------------------------------+
| Plan                                 |
+--------------------------------------+
| └──Project(v)                  |
| └──Limit(1)                    |
| └──HashJoin                    |
| ├──DelimScan(1)                |
| └──DelimProduce(1)             |
| └──NodeScan                    |
+--------------------------------------+
```

Is there anything to do with this?

**Comment by p-ranav** [comment]
`tabulate` performs a trim operation on each line of each cell to remove whitespace characters from either side of line.

Can you try to using the "no trim" mode?

```cpp
outputTable.format().trim_mode(tabulate::Format::TrimMode::kNone);
```

**Comment by p-ranav** [comment]
Two reasons:

1. `tabulate` performs a trim operation on each line of each cell to remove whitespace characters from either side of line.
2. The characters you have there for the tree view are multi-byte characters. So enable multi-byte support in the formatting - that will do the right thing in computing the display width (not the same as character width) for those characters. 

```cpp
#include "tabulate.hpp"
using namespace tabulate;

int main() {
    std::string plan =
	    "└──Project(v)\n"
        "    └──Limit(1)\n"
        "        └──HashJoin\n"
        "            ├──DelimScan(1)\n"
        "            └──DelimProduce(1)\n"
        "                └──NodeScan\n";
        
    Table outputTable;
    outputTable.format()
        .multi_byte_characters(true)
        .trim_mode(Format::TrimMode::kNone);
    outputTable.add_row({"Plan"});
    outputTable.add_row({plan});
    std::cout << outputTable << std::endl;
}
```

prints 

<img width="351" alt="image" src="https://github.com/p-ranav/tabulate/assets/8450091/809d59ae-ed96-430a-a032-8e611af5fdb0">

**Comment by neog24** [comment]
That solve my problem, thanks soooo much!
