### ISSUE TITLE
Support serializing tables to markdown

### ISSUE THREAD

**Issue by p-ranav** [p-ranav/tabulate#20]

**Comment by DeveloperPaul123** [comment]
What types of things should be included in the export options for the `MarkdownExporter`? Do we need options per column and what not? Or can the exporter just pull from the formatter objects to get properties like text alignment and what not?

**Comment by p-ranav** [comment]
For markdown, we probably don't need any ExportOptions. All the formatting is encoded in the format objects. We can just read from this and generate a markdown version of the table.
