### ISSUE TITLE
Support exporting tabulate::table to LaTeX table

### ISSUE THREAD

**Issue by p-ranav** [p-ranav/tabulate#21]

**Comment by DeveloperPaul123** [comment]
I'm interested on working on this issue and #20. What are your initial thoughts on how to approach this? Are you thinking to just have a generic "Exporter" class that can then be specialized to generate the necessary format?

**Comment by p-ranav** [comment]
Thanks for the interest! Sure, here are some thoughts:

We need to prepare a mapping between `tabulate::Format` and LaTeX's table formatting system. For example, 

* How does the width/height measurement in tabulate map to lengths in LaTeX (e.g., 5em, 1cm etc.)
* How does the font alignment map to LaTeX? For example, does `FontAlign::right` generate something like `>{\raggedright\arraybackslash}X`?
* Tabulate doesn't support merging rows, cells etc., while LaTeX does. Should the user be able to specify how to merge cells and generate LaTeX even though tabulate isn't expressive enough to handle this with its own print function?
* What about LaTeX packages? e.g., `multirow` or `longtable`?

I think we can start with something very simple and work our way up. Have an `Exporter` class that we can extend/specialize for different formats sounds good to me. It decouples the data (i.e., the Table class) from the algorithm (i.e., serialization) and can be extended for different formats easily. This will work similarly to how the `Printer` class is currently implemented. For the LaTeX case, the question is: what state does a LatexExporter store and how does it go about generating LaTeX tables?

The interface for a generic Exporter class could be:

```cpp
class Exporter {
public:
  virtual std::string export();
};
``` 

and the LatexExporter could be:

```cpp
class LatexExporter : public Exporter {
public:

  class ExportOptions {
  public:
     // methods to set/get options
  private:
     // options
  }; 
  
  ExportOptions& configure() {
     // return an ExportOptions object that can be used in a fluent interface similar
     // to table.format() to configure the exporter
     return options_;
  }

  std::string export() override {
    // magic happens here
  }
private:
  ExportOptions options_;
};
```

We can create a similar specialization for #20.

**Comment by DeveloperPaul123** [comment]
Awesome, sounds good to me!

**Comment by mlohry** [comment]
> How does the width/height measurement in tabulate map to lengths in LaTeX (e.g., 5em, 1cm etc.)

Since the goal of LaTeX output is presumably to be included in a document with LaTeX handling the fine grain formatting details, I would suggest not encoding measurements at all.

**Comment by p-ranav** [comment]
@DeveloperPaul123 

**UPDATE**: I've implemented [exporting to Markdown](https://github.com/p-ranav/tabulate#markdown) for #20 per our discussion above. Use this as a reference for your LatexExporter. Let me know if you face any issues.

**Comment by DeveloperPaul123** [comment]
@p-ranav Awesome thanks! I had actually started on the Markdown one since I thought it would be easier 😆 but this works too.

**Comment by p-ranav** [comment]
> @p-ranav Awesome thanks! I had actually started on the Markdown one since I thought it would be easier  but this works too.

I feared this would be the case. Apologies.

**Comment by DeveloperPaul123** [comment]
No worries! It would be good to agree on what type of options we want for a latex export. I would argue that it should be as vanilla as possible given that the intention is to include it in a Latex document as pointed out by [mhlohry](https://github.com/p-ranav/tabulate/issues/21#issuecomment-569981334). 

Maybe we can start simple and go with no config options for now and then add more later? Or do you think there is a minimum viable set that would be useful for something like this? I think it makes sense to include things like alignment, but this information is already in the `Format` object.

**Comment by p-ranav** [comment]
Yes, let's start barebones and add options as needed.

**Comment by DeveloperPaul123** [comment]
Sounds good. Did you want me to use the same technique as the markdown exporter (saving the current format, alter it for export and then revert format back to original)?

**Comment by p-ranav** [comment]
Depends on whether we want to support multi-line table cells in the generated LaTeX. For a start, we should probably go with option 1 below:

## Option 1: Just iterate over rows of table

Instead of using the MarkdownExporter approach, It is probably easier just to iterate over rows in the table and construct LaTeX equivalent representation, e.g.,

```cpp
// Untested + incomplete pseudo-code:
std::string result{};
result += "\begin{tabular}";

result += add_column_alignment(); // e.g., "{c c c}"
result += "\n";

for(size_t i = 0; i < table.size(); ++i) {
    auto row = table[i];
    for (size_t j = 0; j < row.size(); ++j) {
        result ++ row[j].get_text();
        if (j + 1 < row.size())
            result += "&";
    }
    if (i + 1 < table.size())
        result += "\\\\";
    result += "\n";
}

result += "\end{tabular}";
return result;
```

This is probably the easiest way as it quickly generates what we need.

```
Example output:

\begin{tabular}{ c c c }
 cell1 & cell2 & cell3 \\ 
 cell4 & cell5 & cell6 \\  
 cell7 & cell8 & cell9    
\end{tabular}
```

**NOTE**: This does not account for cells with multi-line text, e.g.,

```
Name   Employee
       Identif-
       ication

ABC    1234567
DEF    6789106
```

## Option 2: Using `table.str()` similar to MarkdownExporter

Use `table.str()` similar to MarkdownExporter but you'll want to think about how to handle 
table cells with multi-line text. In LaTeX, this can be achieved with 
[nested \begin{tabular}...\end{tabular}](https://tex.stackexchange.com/questions/40561/table-with-multiple-lines-in-some-cells)

We can start with Option 1 and more carefully implement support for multi-line text with nested LaTeX tables.

**Comment by DeveloperPaul123** [comment]
I think what you presented going with option 1 for now is a good first approach.

**Comment by p-ranav** [comment]
@DeveloperPaul123 are you working on this? If not, I'll put some time into this.

**Comment by DeveloperPaul123** [comment]
Yes I'm working on this. I'll have some time this weekend so should be able to file a PR soon. Thanks!
