### ISSUE TITLE
Interactive drawing feature

### ISSUE THREAD

**Issue by xphiyy** [p-ranav/tabulate#27]
Hi guys, thanks for sharing this project. I'm now practicing c++ with new features, and it seems that I can learn much from this project. However, as a tabulation tool, it would be great if it can support _interactive drawing_, like CLING. If it is possible to add this feature in future? #

**Comment by p-ranav** [comment]
Thanks for your suggestion. Such a feature would probably be better suited in a TUI project that is e.g., based on `ncurses` or `termbox`. `tabulate` could be useful in such projects but implementing interactivity _efficiently_ requires better control over the terminal cursor - something that tabulate doesn't currently expect.

Is there an `ncurses`-like library for Modern C++ that is cross-platform? Is there exists such a library, perhaps it can be used in this context for implementing interactivity.
