### ISSUE TITLE
Using tabulate in different Translation Unit leads to multiple definition at link time

### ISSUE THREAD

**Issue by jfalcou** [p-ranav/tabulate#29]
Use Tabulate in two different .cpp and link the result leads to multiple definition errors. 
I think most of the functions in the header shoudl be marked inline.

**Comment by p-ranav** [comment]
Makes sense. Sorry about that. Please confirm that this is fixed now.

**Comment by jfalcou** [comment]
Perfect ! Thanks

**Comment by xgdgsc** [comment]
Oh. A new release should include this.
