### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by marimeireles** [p-ranav/tabulate#40]
Hey @p-ranav, I'd like to use the `shape` tuple that's implemented in the master branch.

I'm one of the maintainers of the conda package and ideally it depends on your git releases to have a conda package release.

Do you have any plans for making a new release?

Thanks a lot =)

**Comment by p-ranav** [comment]
I've published a new release. It's been a while so I'll have to take some time to write the CHANGELOG

**Comment by marimeireles** [comment]
Amazing! 
Thanks :)
