### ISSUE TITLE
add_row signature changed in a backward-incompatible way in 1.3

### ISSUE THREAD

**Issue by SylvainCorlay** [p-ranav/tabulate#44]
First, we are super grateful for this package which is super nice!

FYI, it seems that [this change](https://github.com/p-ranav/tabulate/pull/43/files#diff-24be99217771502f8f7e0b1efe8b7a43R58) is backward incompatible because of the change in the signature.

Maybe this should have been a 2.0 change?

Ping @marimeireles

**Comment by p-ranav** [comment]
Makes sense. Ironically, this change was made to support older C++ compilers. 

Will releasing a v2.0 now solve the issue? If needed, I can delete v1.3 since it breaks compatibility.

**Comment by SylvainCorlay** [comment]
Thank you for responding!

I think it is fine as we are pinning to 1.2 - and will soon update to 1.3!

I just wanted to give you a heads up!

Quick note: as I was going through the commit history, I figured it would help if the release commits were separate from other changes - so that can see which commits occured between two releases :)

**Comment by SylvainCorlay** [comment]
Closing as we have updated xeus-sqlite to use 1.3.
