### ISSUE TITLE
Version 1.3 includes <optional> unconditionaly in column.hpp

### ISSUE THREAD

**Issue by SylvainCorlay** [p-ranav/tabulate#47]
It seems that this is fixed in master, but the last release includes `<optional>` unconditionally while you already provide a polyfill in the source code.

**Comment by p-ranav** [comment]
I've updated the `v1.3` tag to point to latest on `master`. `master` only had a few minor patch commits since `v1.3` so I decided to just bump `v1.3` to latest instead of creating a `v1.4`.

Sorry about the inconsistency. Thanks for reporting the issue.
