### ISSUE TITLE
format border commands have no effect

### ISSUE THREAD

**Issue by mlohry** [p-ranav/tabulate#49]
I'm trying to print tables without any border characters. When I use the `.format().border_top(" ")` etc type of commands, it has no effect and always prints the default +----+ type borders. Similarly using `output_table.format().hide_border();` also has no effect, and still prints with the default borders. Am I using this wrong or is it a bug?

**Comment by p-ranav** [comment]
Here are some simple tests using the single_include version of the library:

### Format border

```cpp
// main.cpp
#include "tabulate.hpp"
#include <iostream>
using namespace	tabulate;

int main() {
  Table t;

  t.add_row({"a", "b", "c"});
  t.add_row({"1", "2", "3"});
  t.add_row({"4", "5", "6"});

  t[0].format().border_top(" ");
  t[1].format().border_top(" ");
  t[2].format().border_top(" ");

  std::cout << t << std::endl;
}
```

and it prints:

```console
$ ./main
+   +   +   +
| a | b | c |
+   +   +   +
| 1 | 2 | 3 |
+   +   +   +
| 4 | 5 | 6 |
+---+---+---+

```

### Hide border

```cpp
#include "tabulate.hpp"
#include <iostream>
using namespace	tabulate;

int main() {
  Table t;

  t.add_row({"a", "b", "c"});
  t.add_row({"1", "2", "3"});
  t.add_row({"4", "5", "6"});

  t.format().hide_border();

  std::cout << t << std::endl;
}
```

```console
▶ ./main
 a  b  c
 1  2  3
 4  5  6


```

As far as I can tell, they have the desired effect. Are you not seeing the same result? If not, can you post your code?

**Comment by mlohry** [comment]
Unfortunately I'm not seeing the same result. This code:

```#include <iostream>
#include <tabulate/table.hpp>

int main(){
  {
    tabulate::Table t;

    t.add_row({"a", "b", "c"});
    t.add_row({"1", "2", "3"});
    t.add_row({"4", "5", "6"});

    t[0].format().border_top(" ");
    t[1].format().border_top(" ");
    t[2].format().border_top(" ");

    std::cout << "with border:\n" << t << std::endl;
  }
  {
    tabulate::Table t;

    t.add_row({"a", "b", "c"});
    t.add_row({"1", "2", "3"});
    t.add_row({"4", "5", "6"});

    t[0].format().border_top(" ");
    t[1].format().border_top(" ");
    t[2].format().border_top(" ");

    t.format().hide_border();

    std::cout << "without border:\n" << t << std::endl;
  }
}
```

results in

```
with border:
+   +   +   +
| a | b | c |
+   +   +   +
| 1 | 2 | 3 |
+   +   +   +
| 4 | 5 | 6 |
+---+---+---+
without border:
+   +   +   +
| a | b | c |
+   +   +   +
| 1 | 2 | 3 |
+   +   +   +
| 4 | 5 | 6 |
+---+---+---+
```

Same result with both g++ 9.3.0 and clang++ 10.0.0. This is on ubuntu 20.04.1 LTS.

**Comment by p-ranav** [comment]
Below _is_ the expected output for `border_top(" ")`. You can see that the first three rows have a border top of `" "` 

***NOTE*** that you don't see `-` above the first three rows. You only see `+` for the corners

***NOTE*** Corners and borders are seen separately in tabulate. 

```console
$ ./main
+   +   +   +
| a | b | c |
+   +   +   +
| 1 | 2 | 3 |
+   +   +   +
| 4 | 5 | 6 |
+---+---+---+
```

As for the second result, this is explained by the style inheritance model:
* Cell-level formatting is prioritized over row-level formatting
* Row-level formatting is prioritized over table-level formatting
* Table-level formatting is prioritized over the default table format

So, instead of indexing into the row and formatting, i.e., `t[0].format().border_top(" ")`, just format at the table level using `t.format().border_top(" ")`. Then it has the same priority as `t.format().hide_border()`. 

```cpp
#include <iostream>
#include <tabulate/table.hpp>

int main(){
  {
    tabulate::Table t;

    t.add_row({"a", "b", "c"});
    t.add_row({"1", "2", "3"});
    t.add_row({"4", "5", "6"});

    t[0].format().border_top(" ");
    t[1].format().border_top(" ");
    t[2].format().border_top(" ");

    std::cout << "with border:\n" << t << std::endl;
  }
  {
    tabulate::Table t;

    t.add_row({"a", "b", "c"});
    t.add_row({"1", "2", "3"});
    t.add_row({"4", "5", "6"});

    t.format().border_top(" ");

    t.format().hide_border();

    std::cout << "without border:\n" << t << std::endl;
  }
}
```

```console
$ ./main
with border:
+   +   +   +
| a | b | c |
+   +   +   +
| 1 | 2 | 3 |
+   +   +   +
| 4 | 5 | 6 |
+---+---+---+
without border:
 a  b  c
 1  2  3
 4  5  6
```

**Comment by mlohry** [comment]
> As for the second result, this is explained by the style inheritance model:

Ah, got it, thanks! I was thinking the other way around -- that the latest command would overwrite anything before it. Makes sense.
