### ISSUE TITLE
New tagged version on github?

### ISSUE THREAD

**Issue by marimeireles** [p-ranav/tabulate#55]
Hey @p-ranav, would be nice to have a new version of `tabulate` on conda :)

I can of course create the new version on conda, but for that I need a new tagged version on github.

Lemme know if you want any help to get this going.

Thanks!

**Comment by p-ranav** [comment]
I can certainly create a `v1.4`. Can you help me compile a CHANGELOG? - The set of changes in v1.4 that can mention in the release notes.

**Comment by marimeireles** [comment]
@p-ranav sure thing =)
Should I change this file? https://github.com/p-ranav/tabulate/blob/master/utils/amalgamate/CHANGES.md

**Comment by p-ranav** [comment]
No, that would be the CHANGELOG for amalgamate. We don't currently have a CHANGELOG file for tabulate in the repo. I've just been adding them in the description box for new releases. Maybe we should create a file in the repo, compiling all the changelog descriptions from the releases.
