### ISSUE TITLE
How to give array as an input in table.add_row()?

### ISSUE THREAD

**Issue by shie-ld** [p-ranav/tabulate#60]
Hey just want to know is there any facility to pass an array or vector to table.add_row() so that required row is generated from arrray/vector itself?

**Comment by p-ranav** [comment]
`table.add_row()` does take a vector: https://github.com/p-ranav/tabulate/blob/master/include/tabulate/table.hpp#L59

Can you elaborate? Do you specifically mean a vector of strings?

**Comment by danillucky1234** [comment]
Yep, I have the same question. I want to put the vector of strings into the table.add_row(), but my compiler (g++ 10.2.0) said:
error: cannot convert ‘std::vector<std::__cxx11::basic_string<char> >’ to ‘const std::vector<nonstd::variants::variant<std::__cxx11::basic_string<char>, const char*, tabulate::Table> >&’. What should do I do?

**Comment by danillucky1234** [comment]
```
        tabulate::Table prettyTable;
	std::vector<variant<std::string, const char *, tabulate::Table>> mapped;

	// set header to our table
	std::vector<std::string> rows;
	for(int i = 1; i < argc; ++i)
	{
		rows.push_back(argv[i]);
	}
	for(const auto& it : rows)
	{
		const auto varRow = variant<std::string, const char *, tabulate::Table>(it);
		mapped.push_back(varRow);
	}

	prettyTable.add_row(mapped);
```
One guy helped me and it all worked. To pass a vector of strings to add_row(), you have to do this loop:
```
	for(const auto& it : rows)
	{
		const auto varRow = variant<std::string, const char *, tabulate::Table>(it);
		mapped.push_back(varRow);
	}
```

**Comment by p-ranav** [comment]
Closing since no response from OP

**Comment by pkjagesia** [comment]
On using the code snippet above, I get the following error. I am on a MAC using c++ 17

no suitable user-defined conversion from "std::__1::vector<nonstd::variants::variant<std::__1::string, const char *, tabulate::Table, nonstd::variants::detail::T3, nonstd::variants::detail::T4, nonstd::variants::detail::T5, nonstd::variants::detail::T6, nonstd::variants::detail::T7, nonstd::variants::detail::T8, nonstd::variants::detail::T9, nonstd::variants::detail::T10, nonstd::variants::detail::T11, nonstd::variants::detail::T12, nonstd::variants::detail::T13, nonstd::variants::detail::T14, nonstd::variants::detail::T15>, std::__1::allocator<nonstd::variants::variant<std::__1::string, const char *, tabulate::Table, nonstd::variants::detail::T3, nonstd::variants::detail::T4, nonstd::variants::detail::T5, nonstd::variants::detail::T6, nonstd::variants::detail::T7, nonstd::variants::detail::T8, nonstd::variants::detail::T9, nonstd::variants::detail::T10, nonstd::variants::detail::T11, nonstd::variants::detail::T12, nonstd::variants::detail::T13, nonstd::variants::detail::T14, nonstd::variants::detail::T15>>>" to "const tabulate::Table::Row_t" exists
