### ISSUE TITLE
How to print it to a file?

### ISSUE THREAD

**Issue by loumalouomega** [p-ranav/tabulate#66]
It is possible to print the table to a file without all the special characters?

**Comment by p-ranav** [comment]
`tabulate` supports exporting to markdown, asciidoc, and latex. See [here](https://github.com/p-ranav/tabulate#markdown) for an example. You could write that table to a file trivially - Use `table.str()` to get a string representation (what you usually see when you print out the table).

**Comment by loumalouomega** [comment]
Thanks, I saw the exporters, but I was looking for plain text. I will try as you say. Thanks, nice lib

**Comment by loumalouomega** [comment]
Yes, it works, thanks a lot
