### ISSUE TITLE
Can i use tabulate in c++11?

### ISSUE THREAD

**Issue by nickhuangxinyu** [p-ranav/tabulate#70]
I read the code, found it use c++17.

but i can only use c++ in my machine, so, Is there a usable version for c++11?

Thanks

**Comment by p-ranav** [comment]
Yes, it does. If C++17 is not supported, it'll use C++11 alongside `optional-lite`, and `variant-lite`. See [here](https://github.com/p-ranav/tabulate/blob/master/include/tabulate/cell.hpp#L41) for an example.

**Comment by p-ranav** [comment]
[Here](https://github.com/p-ranav/tabulate/blob/master/CMakeLists.txt#L39)'s the relevant bit in the CMakeLists of the tabulate samples
