### ISSUE TITLE
how to set decimal's rounding?

### ISSUE THREAD

**Issue by nickhuangxinyu** [p-ranav/tabulate#71]
in Samples movie, if the cell content is double, it will output a lot of .00000

Can I set rounding digit?

**Comment by p-ranav** [comment]
`tabulate` simply takes strings? If you want to format your string, you can do this with streams or libfmt as needed.

**Comment by nickhuangxinyu** [comment]
@p-ranav thanks for reply.

Can you teach me how to realize it?

I add
`std::cout<<setiosflags(std::ios::fixed)<<setprecision(2);`

in table `inline std::ostream &operator<<(std::ostream &stream, const Table &table)` like this:

```
inline std::ostream &operator<<(std::ostream &stream, const Table &table) {
  stream << std::setiosflags(std::ios::fixed) << std::setprecision(2);
  const_cast<Table &>(table).print(stream);
  return stream;
}
```
but it still output a lot of digit
```
+----------+----------+
|   huang  |    asd   |
+----------+----------+
| 1.111111 | 1.000000 |
+----------+----------+
```

can you give me some tips?
