### ISSUE TITLE
What terminal and color scheme do you use?

### ISSUE THREAD

**Issue by ssabeva** [p-ranav/tabulate#84]
I ran the sample code from here (https://github.com/p-ranav/tabulate/blob/master/samples/summary.cpp )
and my terminal gave out not a bright purple (magenta) color, but a dim one. I use GNOME Terminal (photo below)
Thanks!
![image](https://user-images.githubusercontent.com/62669127/161427642-f9f9be68-6a3d-4a78-878f-e5e401b962b5.png)

**Comment by p-ranav** [comment]
Likely [iTerm2](https://iterm2.com) on a MacBook with the default theme.
